// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csrtkebisqfffjgukkxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzcnRrZWJpc3FmZmZqZ3Vra3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDU1NDksImV4cCI6MjA2Mjg4MTU0OX0.i8ZPQ3PEb8s4k16fqzjpE0O4-iyX9SaA4PbsYOgl2Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'noorcare-auth-token',
    detectSessionInUrl: false
  }
});

// Expose supabase globally for browser console scripts & debugging
if (typeof window !== 'undefined') {
  (window as any).supabase = supabase;
}
